import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Light Theme Colors
        "surface": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#3f4946",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#6f7976",
        "outline-variant": "#bfc9c5",
        "surface-tint": "#29685f",
        "primary": "#003630",
        "on-primary": "#ffffff",
        "primary-container": "#034f46",
        "on-primary-container": "#81bfb3",
        "inverse-primary": "#94d2c6",
        "secondary": "#6b48b8",
        "on-secondary": "#ffffff",
        "secondary-container": "#ac8afe",
        "on-secondary-container": "#40168c",
        "tertiary": "#502213",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6b3827",
        "on-tertiary-container": "#eaa38c",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#afefe2",
        "primary-fixed-dim": "#94d2c6",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#055047",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#522e9f",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-tertiary-fixed": "#360f03",
        "on-tertiary-fixed-variant": "#6c3928",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
        "surface-cream": "#FFFFEB",
        "deep-forest": "#034F46",
        "ethereal-purple": "#AD8BFF",
        "ink-charcoal": "#1A1A1A",
        "muted-sage": "#E8EDE0",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1.0rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "max-width-content": "1200px",
        "stack-md": "16px",
        "container-padding": "24px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "unit": "4px",
        // Stitch Spacing
        "margin-desktop": "48px",
        "container-max": "1200px",
        "base": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "sans": ["var(--font-inter)", "sans-serif"],
        "mono": ["var(--font-mono)", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "label-mono": ["var(--font-mono)", "monospace"],
        "display-lg": ["var(--font-inter)", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
